/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.*;
import java.awt.Color;
import java.awt.Font;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.regex.Pattern;
import java.util.List;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author nitro
 */
public class A_Habitat extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(A_Habitat.class.getName());
    private int selectedHabitatId = -1;

    public A_Habitat() {
        initComponents();
        setupTable();
        loadTableData();
        setupPlaceholders();
        this.setSize(800, 635);
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        
        jTable1.getTableHeader().setOpaque(true);
        jTable1.getTableHeader().setBackground(Color.WHITE);
        jTable1.getTableHeader().setForeground(new Color(112,146,63));
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable1.getTableHeader().setAlignmentX(JLabel.CENTER);
        
        ((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(center);
    }
    
    private void setupPlaceholders() {
        removePlaceholder(jTextField5, "Nama habitat");
        removePlaceholder(jTextField6, "Lokasi");
        removePlaceholder(jTextField7, "Ekosistem");
        removePlaceholder(jTextField8, "Luas");
    }
    
    private void removePlaceholder(JTextField field, String placeholder) {
        field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (field.getText().trim().isEmpty()) {
                    field.setText(placeholder);
                }
            }
        });
    }
    
    private void setupTable() {
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() >= 0) {
                loadSelectedRow();
            }
        });
    }
    
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        List<Habitat> listHabitat = Habitat.getAllHabitat();
        for (Habitat habitat : listHabitat) {
            Object[] row = {
                habitat.getIdHabitat(),
                habitat.getNamaHabitat(),
                habitat.getLokasi(),
                habitat.getTipeEkosistem(),
                habitat.getLuasArea(),
                habitat.getKondisi()
            };
            model.addRow(row);
        }
    }
    
    private void loadSelectedRow() {
    int row = jTable1.getSelectedRow();
    if (row >= 0) {
        selectedHabitatId = (int) jTable1.getValueAt(row, 0);
        
        Habitat habitat = Habitat.getHabitatById(selectedHabitatId);
        if (habitat != null) {
            jTextField5.setText(habitat.getNamaHabitat());
            jTextField6.setText(habitat.getLokasi());
            jTextField7.setText(habitat.getTipeEkosistem());
            jTextField8.setText(String.valueOf(habitat.getLuasArea()));
            
            // Perbaikan: Gunakan try-catch untuk menghindari error
            try {
                jComboBox1.setSelectedItem(habitat.getKondisi());
            } catch (Exception e) {
                // Jika error, set ke default (index 0)
                jComboBox1.setSelectedIndex(0);
            }
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 30)); // NOI18N
        jLabel2.setText("KELOLA HABITAT");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 290, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTextField5.setText("Nama habitat");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 84, 41));
        jLabel3.setText("Nama Habitat");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 84, 41));
        jLabel4.setText("Lokasi");

        jTextField6.setText("Lokasi");

        jTextField7.setText("Ekosistem");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 84, 41));
        jLabel5.setText("Tipe Ekosistem");

        jTextField8.setText("Luas");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(68, 84, 41));
        jLabel6.setText("Luas Area");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(68, 84, 41));
        jLabel7.setText("Kondisi");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baik", "Rusak", "Kritis" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 80, 720, 210);

        jButton2.setBackground(new java.awt.Color(112, 146, 63));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hapus");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 300, 110, 30);

        jButton4.setBackground(new java.awt.Color(112, 146, 63));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Buat");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(110, 300, 110, 30);

        jButton3.setBackground(new java.awt.Color(112, 146, 63));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(340, 300, 110, 30);

        jTable1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nama Habitat", "Lokasi", "Tipe Ekosistem", "Luas Area", "Kondisi"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(225, 159, 93));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(41, 340, 720, 200);

        jButton1.setBackground(new java.awt.Color(112, 146, 63));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 550, 85, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_admin.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // edit
        handleEdit();
    }//GEN-LAST:event_jButton3ActionPerformed
    
     private void handleEdit() {
    if (selectedHabitatId == -1) {
        JOptionPane.showMessageDialog(this,
            "Pilih habitat yang ingin diedit!",
            "Peringatan",
            JOptionPane.WARNING_MESSAGE);
        return;
    }
    
    if (!validateInput()) return;
    
    try {
        Habitat habitat = new Habitat();
        habitat.setIdHabitat(selectedHabitatId);
        habitat.setNamaHabitat(getFieldText(jTextField5));
        habitat.setLokasi(getFieldText(jTextField6));
        habitat.setTipeEkosistem(getFieldText(jTextField7));
        
        String luasText = getFieldText(jTextField8);
        double luas = luasText.isEmpty() ? 0 : Double.parseDouble(luasText);
        habitat.setLuasArea(luas);
        
        // PERBAIKAN: Pastikan kondisi tidak null dan di-trim
        String kondisi = jComboBox1.getSelectedItem() != null ? 
                        jComboBox1.getSelectedItem().toString().trim() : "Baik";
        habitat.setKondisi(kondisi);
        
        if (habitat.updateHabitat()) {
            JOptionPane.showMessageDialog(this,
                "Habitat berhasil diupdate!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);
            clearForm();
            loadTableData();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Luas area harus berupa angka!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error saat update: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        logger.log(java.util.logging.Level.SEVERE, "Error update habitat", e);
    }
}
     
    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        handleBuat();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // hapus
        handleHapus();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new A_Menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void handleHapus() {
        if (selectedHabitatId == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih habitat yang ingin dihapus!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus habitat ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            if (Habitat.hapusHabitat(selectedHabitatId)) {
                JOptionPane.showMessageDialog(this,
                    "Habitat berhasil dihapus!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadTableData();
            }
        }
    }
    
     private void handleBuat() {
    if (!validateInput()) return;
    
    try {
        Habitat habitat = new Habitat();
        habitat.setNamaHabitat(getFieldText(jTextField5));
        habitat.setLokasi(getFieldText(jTextField6));
        habitat.setTipeEkosistem(getFieldText(jTextField7));
        
        String luasText = getFieldText(jTextField8);
        double luas = luasText.isEmpty() ? 0 : Double.parseDouble(luasText);
        habitat.setLuasArea(luas);
        
        // PERBAIKAN: Pastikan kondisi tidak null dan di-trim
        String kondisi = jComboBox1.getSelectedItem() != null ? 
                        jComboBox1.getSelectedItem().toString().trim() : "Baik";
        habitat.setKondisi(kondisi);
        
        if (habitat.tambahHabitat()) {
            JOptionPane.showMessageDialog(this,
                "Habitat berhasil ditambahkan!",
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);
            clearForm();
            loadTableData();
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Luas area harus berupa angka!",
            "Error",
            JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
            "Error saat tambah: " + e.getMessage(),
            "Error",
            JOptionPane.ERROR_MESSAGE);
        logger.log(java.util.logging.Level.SEVERE, "Error tambah habitat", e);
    }
}
     
     private boolean containsInvalidCharacters(String text) {
    // Pattern untuk detect special characters yang tidak diperbolehkan
    // Mengizinkan: huruf (a-z, A-Z), angka (0-9), spasi, koma, titik, dash, apostrof
    Pattern invalidPattern = Pattern.compile("[^a-zA-Z0-9\\s,.\\-']");
    return invalidPattern.matcher(text).find();
}
     
     private boolean isValidNumber(String text) {
    if (text == null || text.trim().isEmpty()) {
        return false;
    }
    // Pattern untuk angka dengan optional desimal
    Pattern numberPattern = Pattern.compile("^\\d+(\\.\\d+)?$");
    return numberPattern.matcher(text.trim()).matches();
    }

/**
 * GANTI method validateInput() yang lama dengan yang ini
 */
    
     private boolean validateInput() {
    String nama = getFieldText(jTextField5);
    String lokasi = getFieldText(jTextField6);
    String ekosistem = getFieldText(jTextField7);
    String luasText = getFieldText(jTextField8);
    
    // ========== VALIDASI NAMA HABITAT ==========
    if (nama.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Nama Habitat harus diisi!",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField5.requestFocus();
        return false;
    }
    
    if (containsInvalidCharacters(nama)) {
        JOptionPane.showMessageDialog(this,
            "Nama Habitat tidak boleh mengandung karakter khusus!\n" +
            "Hanya diperbolehkan: huruf, angka, spasi, koma, titik, dash (-), apostrof (')",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField5.requestFocus();
        return false;
    }
    
    if (nama.length() < 3) {
        JOptionPane.showMessageDialog(this,
            "Nama Habitat minimal 3 karakter!",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField5.requestFocus();
        return false;
    }
    
    if (nama.length() > 100) {
        JOptionPane.showMessageDialog(this,
            "Nama Habitat maksimal 100 karakter!",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField5.requestFocus();
        return false;
    }
    
    // ========== VALIDASI LOKASI ==========
    if (lokasi.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Lokasi harus diisi!",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField6.requestFocus();
        return false;
    }
    
    if (containsInvalidCharacters(lokasi)) {
        JOptionPane.showMessageDialog(this,
            "Lokasi tidak boleh mengandung karakter khusus!\n" +
            "Hanya diperbolehkan: huruf, angka, spasi, koma, titik, dash (-)",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField6.requestFocus();
        return false;
    }
    
    if (lokasi.length() < 3) {
        JOptionPane.showMessageDialog(this,
            "Lokasi minimal 3 karakter!",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField6.requestFocus();
        return false;
    }
    
    // ========== VALIDASI TIPE EKOSISTEM ==========
    if (ekosistem.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Tipe Ekosistem harus diisi!",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField7.requestFocus();
        return false;
    }
    
    if (containsInvalidCharacters(ekosistem)) {
        JOptionPane.showMessageDialog(this,
            "Tipe Ekosistem tidak boleh mengandung karakter khusus!\n" +
            "Hanya diperbolehkan: huruf, angka, spasi",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField7.requestFocus();
        return false;
    }
    
    if (ekosistem.length() < 3) {
        JOptionPane.showMessageDialog(this,
            "Tipe Ekosistem minimal 3 karakter!",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField7.requestFocus();
        return false;
    }
    
    // ========== VALIDASI LUAS AREA ==========
    if (luasText.isEmpty()) {
        JOptionPane.showMessageDialog(this,
            "Luas Area harus diisi!",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField8.requestFocus();
        return false;
    }
    
    if (!isValidNumber(luasText)) {
        JOptionPane.showMessageDialog(this,
            "Luas Area harus berupa angka!\n" +
            "Contoh: 100 atau 100.5",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField8.requestFocus();
        return false;
    }
    
    try {
        double luas = Double.parseDouble(luasText);
        
        if (luas <= 0) {
            JOptionPane.showMessageDialog(this,
                "Luas Area harus lebih dari 0!",
                "Validasi Gagal",
                JOptionPane.WARNING_MESSAGE);
            jTextField8.requestFocus();
            return false;
        }
        
        if (luas > 999999.99) {
            JOptionPane.showMessageDialog(this,
                "Luas Area maksimal 999999.99!",
                "Validasi Gagal",
                JOptionPane.WARNING_MESSAGE);
            jTextField8.requestFocus();
            return false;
        }
        
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this,
            "Format Luas Area tidak valid!",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jTextField8.requestFocus();
        return false;
    }
    
    // ========== VALIDASI KONDISI ==========
    if (jComboBox1.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this,
            "Kondisi harus dipilih!",
            "Validasi Gagal",
            JOptionPane.WARNING_MESSAGE);
        jComboBox1.requestFocus();
        return false;
    }
    
    return true;
}
     
    private String getFieldText(JTextField field) {
    String text = field.getText().trim();
    if (text.equals("Nama habitat") || text.equals("Lokasi") || 
        text.equals("Ekosistem") || text.equals("Luas")) {
        return "";
    }
    return text;
    }
    
    private void clearForm() {
        jTextField5.setText("Nama habitat");
        jTextField6.setText("Lokasi");
        jTextField7.setText("Ekosistem");
        jTextField8.setText("Luas");
        jComboBox1.setSelectedIndex(0);
        selectedHabitatId = -1;
        jTable1.clearSelection();
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> new A_Habitat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
