/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.List;

/**
 *
 * @author nitro
 */
public class A_plh extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(A_plh.class.getName());
    private int selectedPemeliharaanId = -1;

    public A_plh() {
        initComponents();
        setupTable();
        loadTableData();
        setupTextArea();
        this.setSize(800, 635);
        this.setResizable(true);
        this.setLocationRelativeTo(null);
    }
    
    private void setupTextArea() {
        // Setup jScrollPane2 with JTextArea for keterangan
        JTextArea txtKeterangan = new JTextArea();
        txtKeterangan.setLineWrap(true);
        txtKeterangan.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtKeterangan);
    }
    
    private void setupTable() {
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() >= 0) {
                loadSelectedRow();
            }
        });
    }
    
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        List<Pemeliharaan> listPemeliharaan = Pemeliharaan.getAllPemeliharaan();
        for (Pemeliharaan p : listPemeliharaan) {
            Object[] row = {
                p.getIdPemeliharaan(),
                p.getTanggalPemeliharaan(),
                p.getKegiatan(),
                p.getHasilPemeliharaan(),
                p.getStatusVerifikasi(),
                p.getTanggalVerifikasi(),
                p.getKeterangan()
            };
            model.addRow(row);
        }
    }
    
    private void loadSelectedRow() {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            selectedPemeliharaanId = (int) jTable1.getValueAt(row, 0);
            
            // Set status
            String status = (String) jTable1.getValueAt(row, 4);
            jComboBox1.setSelectedItem(status);
            
            // Set keterangan if exists
            String keterangan = (String) jTable1.getValueAt(row, 6);
            if (keterangan != null) {
                JTextArea txtKeterangan = (JTextArea) jScrollPane2.getViewport().getView();
                txtKeterangan.setText(keterangan);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 30)); // NOI18N
        jLabel2.setText("LAPORAN PEMELIHARAAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 410, 50);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tgl Pemeliharaan", "Kegiatan", "Hasil", "Status", "Tgl Verifikasi", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(225, 159, 93));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 290, 720, 240);

        jButton1.setBackground(new java.awt.Color(112, 146, 63));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 550, 90, 27);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(68, 84, 41));
        jLabel3.setText("Tanggal Verifikasi");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 128, -1));

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 84, 41));
        jLabel4.setText("Status");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 128, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Menunggu", "Diverifikasi", "Ditolak" }));
        jPanel2.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 174, 30));

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 84, 41));
        jLabel5.setText("Keterangan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 128, -1));

        jButton2.setBackground(new java.awt.Color(112, 146, 63));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, 30));

        jButton3.setBackground(new java.awt.Color(112, 146, 63));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Lihat Detail");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 150, -1, 31));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 440, 100));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 150, 30));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 80, 720, 190);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_admin.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        // Button Lihat Detail
        if (selectedPemeliharaanId == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih laporan untuk melihat detail!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            String detail = "Detail Laporan Pemeliharaan:\n\n" +
                "ID: " + jTable1.getValueAt(row, 0) + "\n" +
                "Tanggal: " + jTable1.getValueAt(row, 1) + "\n" +
                "Kegiatan: " + jTable1.getValueAt(row, 2) + "\n" +
                "Hasil: " + jTable1.getValueAt(row, 3) + "\n" +
                "Status: " + jTable1.getValueAt(row, 4) + "\n" +
                "Keterangan: " + jTable1.getValueAt(row, 6);
            
            JOptionPane.showMessageDialog(this,
                detail,
                "Detail Laporan",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        handleSimpan();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new A_Menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        if("date".equals(evt.getPropertyName())) {
            java.util.Date selectedDate = jDateChooser1.getDate();
            if(selectedDate != null) {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
                System.out.println("Tanggal verifikasi dipilih: " + sdf.format(selectedDate));
            } else {
                System.out.println("Tanggal verifikasi dihapus atau dikosongkan.");
            }
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange
    
    private void handleSimpan() {
        if (selectedPemeliharaanId == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih laporan yang ingin diverifikasi!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            String status = (String) jComboBox1.getSelectedItem();
            java.util.Date selectedDate = jDateChooser1.getDate();
            
            java.sql.Date tanggalVerif = null;
            if (selectedDate != null) {
                tanggalVerif = new java.sql.Date(selectedDate.getTime());
            }
            
            JTextArea txtKeterangan = (JTextArea) jScrollPane2.getViewport().getView();
            String keterangan = txtKeterangan.getText().trim();
            
            Admin currentAdmin = SessionManager.getInstance().getCurrentAdmin();
            int idAdmin = currentAdmin != null ? currentAdmin.getIdAdmin() : 1;
            
            if (Pemeliharaan.verifikasiPemeliharaan(selectedPemeliharaanId, 
                status, tanggalVerif, keterangan, idAdmin)) {
                
                JOptionPane.showMessageDialog(this,
                    "Laporan berhasil diverifikasi!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                
                clearForm();
                loadTableData();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
        private void clearForm() {
        jComboBox1.setSelectedIndex(0);
        JTextArea txtKeterangan = (JTextArea) jScrollPane2.getViewport().getView();
        txtKeterangan.setText("");
        selectedPemeliharaanId = -1;
        jTable1.clearSelection();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> new A_plh().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
