/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.*;
import javax.swing.*;
import java.sql.Date;

/**
 *
 * @author nitro
 */
public class Lap_Form extends javax.swing.JFrame {
    
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Lap_Form.class.getName());
    private int pengamatanId = -1;
    private boolean isEditMode = false;

    // Constructor for Create mode
    public Lap_Form() {
        initComponents();
        isEditMode = false;
        setupPlaceholders();
        this.setSize(800, 635);
        this.setResizable(true);
        this.setLocationRelativeTo(null);
    }
    
    // Constructor for Edit mode
    public Lap_Form(int pengamatanId) {
        initComponents();
        this.pengamatanId = pengamatanId;
        this.isEditMode = true;
        setupPlaceholders();
        loadPengamatanData();
        
        this.setSize(800, 600);
        this.setLocationRelativeTo(null);
    }
    
    private void setupPlaceholders() {
        removePlaceholder(jTextField7, "Jumlah");
    }
    
    private void removePlaceholder(JTextField field, String placeholder) {
        field.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (field.getText().equals(placeholder)) {
                    field.setText("");
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (field.getText().trim().isEmpty()) {
                    field.setText(placeholder);
                }
            }
        });
    }
    
    private void loadPengamatanData() {
        try {
            java.sql.Connection conn = Koneksi.getKoneksi();
            String query = "SELECT * FROM pengamatan WHERE id_pengamatan = ?";
            java.sql.PreparedStatement ps = conn.prepareStatement(query);
            ps.setInt(1, pengamatanId);
            java.sql.ResultSet rs = ps.executeQuery();
            
            if (rs.next()) {
                jTextField7.setText(String.valueOf(rs.getInt("jumlah_teramati")));
                jTextArea1.setText(rs.getString("perilaku_satwa"));
                jTextArea2.setText(rs.getString("kondisi_lingkungan"));
                jTextArea3.setText(rs.getString("catatan_tambahan"));
            }
            
            rs.close();
            ps.close();
            Koneksi.closeKoneksi();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error loading data: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 30)); // NOI18N
        jLabel2.setText("PETUGAS LAPANGAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 410, 50);

        jButton1.setBackground(new java.awt.Color(112, 146, 63));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 550, 90, 27);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(68, 84, 41));
        jLabel14.setText("Catatan");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 20, 180, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(68, 84, 41));
        jLabel13.setText("Kondisi Lingkungan");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 159, 28));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(68, 84, 41));
        jLabel12.setText("Perilaku Satwa");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 159, 28));

        jTextField7.setText("Jumlah");
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, 31));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(68, 84, 41));
        jLabel11.setText("Jumlah Teramati");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 159, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(68, 84, 41));
        jLabel10.setText("Tanggal Pengamatan");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 159, 30));

        jButton2.setBackground(new java.awt.Color(112, 146, 63));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Simpan");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 370, -1, 30));
        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 160, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 290, 90));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 290, -1));

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane4.setViewportView(jTextArea3);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 290, 90));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 80, 720, 440);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_admin.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        handleSimpan();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Lap_Menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            java.util.Date tanggalDipilih = jDateChooser1.getDate();
            if (tanggalDipilih != null) {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd MMMM yyyy");
                System.out.println("Tanggal dipilih: " + sdf.format(tanggalDipilih));
            }
        }
    }//GEN-LAST:event_jDateChooser1PropertyChange
    
    private void handleSimpan() {
        if (!validateInput()) return;
        
        try {
            PetugasLapangan petugas = SessionManager.getInstance().getCurrentPetugasLapangan();
            if (petugas == null) {
                JOptionPane.showMessageDialog(this,
                    "Session tidak valid!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            Pengamatan pengamatan = new Pengamatan();
            
            java.util.Date tanggalDipilih = jDateChooser1.getDate();
            if (tanggalDipilih == null) {
                JOptionPane.showMessageDialog(this,
                        "Tanggal pengamatan harus diisi!",
                        "Validasi",
                        JOptionPane.WARNING_MESSAGE);
                return;
            }
            Date tanggalSQL = new Date(tanggalDipilih.getTime());
            pengamatan.setTanggalPengamatan(tanggalSQL);
            pengamatan.setIdPetugasLapangan(petugas.getIdPetugasLapangan());

            pengamatan.setIdHabitat(1);
            pengamatan.setIdSatwa(1);
            
            String jumlahText = getFieldText(jTextField7);
            int jumlah = jumlahText.isEmpty() ? 0 : Integer.parseInt(jumlahText);
            pengamatan.setJumlahTeramati(jumlah);
            
            pengamatan.setPerilakuSatwa(jTextArea1.getText().trim());
            pengamatan.setKondisiLingkungan(jTextArea2.getText().trim());
            pengamatan.setCatatanTambahan(jTextArea3.getText().trim());
            
            if (isEditMode) {
                pengamatan.setIdPengamatan(pengamatanId);
                if (pengamatan.updatePengamatan()) {
                    JOptionPane.showMessageDialog(this,
                        "Pengamatan berhasil diupdate!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    new Lap_Menu().setVisible(true);
                }
            } else {
                if (pengamatan.tambahPengamatan()) {
                    JOptionPane.showMessageDialog(this,
                        "Pengamatan berhasil ditambahkan!",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    new Lap_Menu().setVisible(true);
                }
            }
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                "Jumlah teramati harus berupa angka!",
                "Error",
                JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private boolean validateInput() {
        String jumlah = getFieldText(jTextField7);
        
        if (jumlah.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Jumlah teramati harus diisi!",
                "Validasi",
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    private String getFieldText(JTextField field) {
        String text = field.getText().trim();
        if (text.equals("Jumlah")) {
            return "";
        }
        return text;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> new Lap_Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables
}
