/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.*;
import java.awt.Color;
import java.awt.Font;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author nitro
 */
public class Lap_Menu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Lap_Menu.class.getName());
    private int selectedPengamatanId = -1;

    public Lap_Menu() {
        initComponents();
        setupTable();
        loadTableData();
        setupPlaceholder();
        this.setSize(800, 635);
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        
        jTable1.getTableHeader().setOpaque(true);
        jTable1.getTableHeader().setBackground(Color.WHITE);
        jTable1.getTableHeader().setForeground(new Color(112,146,63));
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable1.getTableHeader().setAlignmentX(JLabel.CENTER);
        
        ((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(center);
    }
    
    private void setupPlaceholder() {
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (jTextField2.getText().equals("Lokasi")) {
                    jTextField2.setText("");
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextField2.getText().trim().isEmpty()) {
                    jTextField2.setText("Lokasi");
                }
            }
        });
    }
    
    private void setupTable() {
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() >= 0) {
                loadSelectedRow();
            }
        });
    }
    
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        // Get current petugas lapangan
        PetugasLapangan petugas = SessionManager.getInstance().getCurrentPetugasLapangan();
        if (petugas != null) {
            List<Pengamatan> listPengamatan = Pengamatan.getAllPengamatan();
            
            for (Pengamatan p : listPengamatan) {
                // Filter by current petugas
                if (p.getIdPetugasLapangan() == petugas.getIdPetugasLapangan()) {
                    Object[] row = {
                        p.getIdPengamatan(),
                        p.getTanggalPengamatan(),
                        p.getPerilakuSatwa(),
                        p.getKondisiLingkungan(),
                        p.getCatatanTambahan(),
                        p.getStatusVerifikasi(),
                        p.getTanggalVerifikasi(),
                        "" // Keterangan
                    };
                    model.addRow(row);
                }
            }
        }
    }
    
    private void loadSelectedRow() {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            selectedPengamatanId = (int) jTable1.getValueAt(row, 0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuLogin1 = new View.MenuLogin();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(68, 84, 41));
        jLabel4.setText("Lokasi");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 70, 128, 20);

        jLabel5.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(68, 84, 41));
        jLabel5.setText("Tanggal Pengamatan");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(20, 6, 159, 22);

        jTextField2.setText("Lokasi");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(20, 90, 256, 36);

        jButton6.setBackground(new java.awt.Color(112, 146, 63));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("OK");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6);
        jButton6.setBounds(290, 90, 54, 35);

        jButton3.setBackground(new java.awt.Color(112, 146, 63));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Lihat Detail");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(587, 33, 110, 35);

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel2.add(jDateChooser1);
        jDateChooser1.setBounds(20, 30, 159, 28);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 80, 720, 140);

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 30)); // NOI18N
        jLabel2.setText("PETUGAS LAPANGAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 410, 50);

        jButton7.setBackground(new java.awt.Color(112, 146, 63));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Log Out");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(665, 30, 90, 30);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tgl Pengamatan", "Perilaku", "Lingkungan", "Catatan", "Status", "Tgl Verifikasi", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setSelectionBackground(new java.awt.Color(225, 159, 93));
        jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 270, 720, 260);

        jButton4.setBackground(new java.awt.Color(112, 146, 63));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Buat");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(130, 230, 90, 35);

        jButton9.setBackground(new java.awt.Color(112, 146, 63));
        jButton9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Edit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(350, 230, 90, 35);

        jButton8.setBackground(new java.awt.Color(112, 146, 63));
        jButton8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Hapus");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(550, 230, 90, 35);

        jLabel1.setBackground(new java.awt.Color(112, 136, 99));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_admin.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Button Lihat Detail
        if (selectedPengamatanId == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih laporan untuk melihat detail!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            String detail = "Detail Laporan:\n\n" +
                "ID: " + jTable1.getValueAt(row, 0) + "\n" +
                "Tanggal: " + jTable1.getValueAt(row, 1) + "\n" +
                "Perilaku Satwa: " + jTable1.getValueAt(row, 2) + "\n" +
                "Kondisi: " + jTable1.getValueAt(row, 3) + "\n" +
                "Catatan: " + jTable1.getValueAt(row, 4) + "\n" +
                "Status: " + jTable1.getValueAt(row, 5);
            
            JOptionPane.showMessageDialog(this,
                detail,
                "Detail Laporan",
                JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Lap_Form form = new Lap_Form();
        form.setVisible(true);
        form.setSize(800, 635);
        form.setLocationRelativeTo(null);
        this.dispose();
        
        form.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadTableData();
            }
        });
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (selectedPengamatanId == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih laporan yang ingin dihapus!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Check if status is still "Menunggu"
        int row = jTable1.getSelectedRow();
        String status = (String) jTable1.getValueAt(row, 5);
        
        if (!status.equals("Menunggu")) {
            JOptionPane.showMessageDialog(this,
                "Hanya laporan dengan status 'Menunggu' yang dapat dihapus!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus laporan ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            if (Pengamatan.hapusPengamatan(selectedPengamatanId)) {
                JOptionPane.showMessageDialog(this,
                    "Laporan berhasil dihapus!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                selectedPengamatanId = -1;
                loadTableData();
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        if (selectedPengamatanId == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih laporan yang ingin diedit!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Check if status is still "Menunggu"
        int row = jTable1.getSelectedRow();
        String status = (String) jTable1.getValueAt(row, 5);
        
        if (!status.equals("Menunggu")) {
            JOptionPane.showMessageDialog(this,
                "Hanya laporan dengan status 'Menunggu' yang dapat diedit!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        this.dispose();
        Lap_Form form = new Lap_Form(selectedPengamatanId);
        form.setSize(800, 635);
        form.setLocationRelativeTo(null);
        form.setVisible(true);
        
        form.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent e) {
                loadTableData();
            }
        });
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        handleFilter();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        handleLogout();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            handleFilter();
        }
        
    }//GEN-LAST:event_jDateChooser1PropertyChange

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
    
     private void handleLogout() {
        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin logout?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            SessionManager.getInstance().logout();
            this.dispose();
            new MenuLogin().setVisible(true);
        }
    }
    private void handleFilter() {
        
        String lokasi = jTextField2.getText().trim();
        if (lokasi.equals("Lokasi")) lokasi = "";
        
        java.util.Date tanggalDipilih = jDateChooser1.getDate();
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        PetugasLapangan petugas = SessionManager.getInstance().getCurrentPetugasLapangan();
        if (petugas == null) return;
        
        List<Pengamatan> listPengamatan = Pengamatan.getAllPengamatan();
        
        for (Pengamatan p : listPengamatan) {
            if (p.getIdPetugasLapangan() != petugas.getIdPetugasLapangan()) continue;
            boolean cocokLokasi = lokasi.equals("Lokasi") || lokasi.isEmpty() ||
                    (p.getLokasi() != null && p.getLokasi().toLowerCase().contains(lokasi.toLowerCase()));
            boolean cocokTanggal = tanggalDipilih == null ||
                    (p.getTanggalPengamatan() != null &&
                    p.getTanggalPengamatan().compareTo(new java.sql.Date(tanggalDipilih.getTime())) == 0);
            if (cocokLokasi && cocokTanggal) {
                Object[] row = {
                        p.getIdPengamatan(),
                        p.getTanggalPengamatan(),
                        p.getPerilakuSatwa(),
                        p.getKondisiLingkungan(),
                        p.getCatatanTambahan(),
                        p.getStatusVerifikasi(),
                        p.getTanggalVerifikasi(),
                        ""
                    };
                    model.addRow(row);
                }
            }
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> new Lap_Menu().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private View.MenuLogin menuLogin1;
    // End of variables declaration//GEN-END:variables
}
