/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.*;
import javax.swing.*;
/**
 *
 * @author nitro
 */
public class MenuLogin extends javax.swing.JFrame {
    
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuLogin.class.getName());
    
    public MenuLogin() {
        initComponents();
        setupPlaceholders();
        this.setSize(800, 635);
        this.setResizable(true);
        this.setLocationRelativeTo(null);
    }
    
    // Setup placeholder behavior
    private void setupPlaceholders() {
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (jTextField1.getText().trim().equals("username")) {
                    jTextField1.setText("");
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (jTextField1.getText().trim().isEmpty()) {
                    jTextField1.setText("username");
                }
            }
        });
        
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                String pass = new String(jPasswordField1.getPassword());
                if (pass.equals("jPasswordField1")) {
                    jPasswordField1.setText("");
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                String pass = new String(jPasswordField1.getPassword());
                if (pass.trim().isEmpty()) {
                    jPasswordField1.setText("jPasswordField1");
                }
            }
        });
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextField1.setBackground(new java.awt.Color(132, 165, 115));
        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField1.setText(" username");
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(410, 220, 330, 40);

        jLabel1.setFont(new java.awt.Font("Myanmar Text", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(109, 136, 82));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Sign In to SIMATA");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(405, 90, 310, 62);

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(112, 136, 99));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(410, 180, 180, 40);

        jButton3.setBackground(new java.awt.Color(106, 125, 91));
        jButton3.setFont(new java.awt.Font("Myanmar Text", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Sign In");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(625, 400, 90, 34);

        jLabel3.setFont(new java.awt.Font("Myanmar Text", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(112, 136, 99));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(410, 280, 113, 30);

        jPasswordField1.setBackground(new java.awt.Color(132, 165, 115));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(410, 320, 330, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_login.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
         jPasswordField1.requestFocus();
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         handleLogin();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        jButton3ActionPerformed(evt);
    }//GEN-LAST:event_jPasswordField1ActionPerformed
    
      private void handleLogin() {
        String username = jTextField1.getText().trim();
        String password = new String(jPasswordField1.getPassword());
        
        // Validasi placeholder
        if (username.equals("username") || username.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Username harus diisi!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (password.equals("jPasswordField1") || password.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Password harus diisi!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Test koneksi database
        if (!Koneksi.testKoneksi()) {
            JOptionPane.showMessageDialog(this,
                "Koneksi database gagal!\nPeriksa konfigurasi database.",
                "Error Koneksi",
                JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Proses login
        User user = User.login(username, password);
        
        if (user != null) {
            // Set session
            SessionManager.getInstance().setCurrentUser(user);
            
            JOptionPane.showMessageDialog(this,
                "Login berhasil!\nSelamat datang, " + user.getNama(),
                "Sukses",
                JOptionPane.INFORMATION_MESSAGE);
            
            // Redirect based on role
            redirectBasedOnRole(user.getRole());
            
            // Close login form
            this.dispose();
            
        } else {
            JOptionPane.showMessageDialog(this,
                "Username atau Password salah!",
                "Login Gagal",
                JOptionPane.ERROR_MESSAGE);
            jPasswordField1.setText("");
            jTextField1.requestFocus();
        }
    }
    
    private void redirectBasedOnRole(String role) {
        switch (role) {
            case "Admin":
                new A_Menu().setVisible(true);
                break;
            case "Petugas Lapangan":
                new Lap_Menu().setVisible(true);
                break;
            case "Petugas Pemeliharaan":
                new Plh_Menu().setVisible(true);
                break;
            default:
                JOptionPane.showMessageDialog(this,
                    "Role tidak dikenali!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
         try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> new A_Menu().setVisible(true));
    }
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
