/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Model.*;
import java.awt.Color;
import java.awt.Font;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.Date;
import java.util.List;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author nitro
 */
public class Plh_Form extends javax.swing.JFrame {
    
   private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Plh_Form.class.getName());
    private int selectedPemeliharaanId = -1;

    public Plh_Form() {
        initComponents();
        setupTable();
        loadTableData();
        this.setSize(800, 635);
        this.setResizable(true);
        this.setLocationRelativeTo(null);
        
        jTable1.getTableHeader().setOpaque(true);
        jTable1.getTableHeader().setBackground(Color.WHITE);
        jTable1.getTableHeader().setForeground(new Color(112,146,63));
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable1.getTableHeader().setAlignmentX(JLabel.CENTER);
        
        ((DefaultTableCellRenderer) jTable1.getTableHeader().getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
        
        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getColumnModel().getColumn(0).setCellRenderer(center);
    }
    
    private void setupTable() {
        jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting() && jTable1.getSelectedRow() >= 0) {
                loadSelectedRow();
            }
        });
    }
    
    private void loadTableData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        
        PetugasPemeliharaan petugas = SessionManager.getInstance().getCurrentPetugasPemeliharaan();
        if (petugas != null) {
            List<Pemeliharaan> listPemeliharaan = 
                Pemeliharaan.getPemeliharaanByPetugas(petugas.getIdPetugasPemeliharaan());
            
            for (Pemeliharaan p : listPemeliharaan) {
                Object[] row = {
                    p.getIdPemeliharaan(),
                    p.getTanggalPemeliharaan(),
                    p.getKegiatan(),
                    p.getHasilPemeliharaan(),
                    p.getStatusVerifikasi(),
                    p.getTanggalVerifikasi(),
                    p.getKeterangan()
                };
                model.addRow(row);
            }
        }
    }
    
    private void loadSelectedRow() {
        int row = jTable1.getSelectedRow();
        if (row >= 0) {
            selectedPemeliharaanId = (int) jTable1.getValueAt(row, 0);
            
            // Load data to form
            JTextArea txtKegiatan = (JTextArea) jScrollPane5.getViewport().getView();
            JTextArea txtHasil = (JTextArea) jScrollPane4.getViewport().getView();
            
            txtKegiatan.setText((String) jTable1.getValueAt(row, 2));
            txtHasil.setText((String) jTable1.getValueAt(row, 3));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Tgl Pemeliharaan", "Kegiatan", "Hasil", "Status", "Tgl Verifikasi", "Keterangan"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 300, 720, 230);

        jLabel2.setFont(new java.awt.Font("Myanmar Text", 1, 30)); // NOI18N
        jLabel2.setText("PETUGAS PEMELIHARAAN");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 30, 410, 50);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Hasil Pemeliharaan");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 6, 159, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Tanggal Pemeliharaan");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 6, 159, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Kegiatan");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 159, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        jPanel2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 300, 70));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 96, 300, 60));

        jDateChooser1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooser1PropertyChange(evt);
            }
        });
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 160, 30));

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 80, 720, 170);

        jButton2.setBackground(new java.awt.Color(112, 146, 63));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(590, 260, 110, 30);

        jButton4.setBackground(new java.awt.Color(112, 146, 63));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Buat");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(100, 260, 110, 30);

        jButton3.setBackground(new java.awt.Color(112, 146, 63));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Edit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(340, 260, 110, 30);

        jButton1.setBackground(new java.awt.Color(112, 146, 63));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Kembali");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 550, 90, 27);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/bg_admin.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        handleUpdate();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        handleCreate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        handleDelete();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new Plh_Menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jDateChooser1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooser1PropertyChange
        // TODO add your handling code here:
        if ("date".equals(evt.getPropertyName())) {
            java.util.Date tanggalDipilih = jDateChooser1.getDate();
            if (tanggalDipilih != null) {
                java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd-MM-yyyy");
                System.out.println("Tanggal pemeliharaan dipilih: " + sdf.format(tanggalDipilih));
            } else{
                System.out.println("Tanggal pemeliharaan dihapus atau dikosongkan.");
            }
        }
        Date sqlDate = null;
    }//GEN-LAST:event_jDateChooser1PropertyChange
    
    private void handleDelete() {
        if (selectedPemeliharaanId == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih pemeliharaan yang ingin dihapus!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Check if status is still "Menunggu"
        int row = jTable1.getSelectedRow();
        String status = (String) jTable1.getValueAt(row, 4);
        
        if (!status.equals("Menunggu")) {
            JOptionPane.showMessageDialog(this,
                "Hanya pemeliharaan dengan status 'Menunggu' yang dapat dihapus!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah Anda yakin ingin menghapus pemeliharaan ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            if (Pemeliharaan.hapusPemeliharaan(selectedPemeliharaanId)) {
                JOptionPane.showMessageDialog(this,
                    "Pemeliharaan berhasil dihapus!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadTableData();
            }
        }
    }
    
    private boolean validateInput() {
        JTextArea txtKegiatan = (JTextArea) jScrollPane5.getViewport().getView();
        
        if (txtKegiatan.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Kegiatan harus diisi!",
                "Validasi",
                JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }
    
    private void clearForm() {
        JTextArea txtKegiatan = (JTextArea) jScrollPane5.getViewport().getView();
        JTextArea txtHasil = (JTextArea) jScrollPane4.getViewport().getView();
        
        txtKegiatan.setText("");
        txtHasil.setText("");
        
        selectedPemeliharaanId = -1;
        jTable1.clearSelection();
    }
    
    private void handleCreate() {
        if (!validateInput()) return;
        
        try {
            PetugasPemeliharaan petugas = SessionManager.getInstance().getCurrentPetugasPemeliharaan();
            if (petugas == null) {
                JOptionPane.showMessageDialog(this,
                    "Session tidak valid!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
                return;
            }
            java.util.Date tanggalDipilih = jDateChooser1.getDate();
            Date tanggalPemeliharaan = new Date(tanggalDipilih.getTime());
            
            Pemeliharaan pemeliharaan = new Pemeliharaan();
            pemeliharaan.setIdPetugasPemeliharaan(petugas.getIdPetugasPemeliharaan());
            pemeliharaan.setIdSatwa(1); // Default, should be selected by user
            pemeliharaan.setTanggalPemeliharaan(new Date(System.currentTimeMillis()));
            
            JTextArea txtKegiatan = (JTextArea) jScrollPane5.getViewport().getView();
            JTextArea txtHasil = (JTextArea) jScrollPane4.getViewport().getView();
            
            pemeliharaan.setKegiatan(txtKegiatan.getText().trim());
            pemeliharaan.setHasilPemeliharaan(txtHasil.getText().trim());
            
            if (pemeliharaan.tambahPemeliharaan()) {
                JOptionPane.showMessageDialog(this,
                    "Pemeliharaan berhasil ditambahkan!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadTableData();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void handleUpdate() {
        if (selectedPemeliharaanId == -1) {
            JOptionPane.showMessageDialog(this,
                "Pilih pemeliharaan yang ingin diupdate!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Check if status is still "Menunggu"
        int row = jTable1.getSelectedRow();
        String status = (String) jTable1.getValueAt(row, 4);
        
        if (!status.equals("Menunggu")) {
            JOptionPane.showMessageDialog(this,
                "Hanya pemeliharaan dengan status 'Menunggu' yang dapat diupdate!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (!validateInput()) return;
        
        try {
            java.util.Date tanggalDipilih = jDateChooser1.getDate();
            Date tanggalPemeliharaan = new Date(tanggalDipilih.getTime());
            
            Pemeliharaan pemeliharaan = new Pemeliharaan();
            pemeliharaan.setIdPemeliharaan(selectedPemeliharaanId);
            pemeliharaan.setIdSatwa(1); // Default, should be selected by user
            pemeliharaan.setTanggalPemeliharaan(new Date(System.currentTimeMillis()));
            
            JTextArea txtKegiatan = (JTextArea) jScrollPane5.getViewport().getView();
            JTextArea txtHasil = (JTextArea) jScrollPane4.getViewport().getView();
            
            pemeliharaan.setKegiatan(txtKegiatan.getText().trim());
            pemeliharaan.setHasilPemeliharaan(txtHasil.getText().trim());
            
            if (pemeliharaan.updatePemeliharaan()) {
                JOptionPane.showMessageDialog(this,
                    "Pemeliharaan berhasil diupdate!",
                    "Sukses",
                    JOptionPane.INFORMATION_MESSAGE);
                clearForm();
                loadTableData();
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                "Error: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> new Plh_Form().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
